name: Deploying

on:
  push:
    branches:
      - testt

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
     
    steps: 
    - name: Deploy app
      uses: victorargento/pm2-deployment@main
      with:
       remote-path: "/home/jatin_naudiyal/fdi-payment-service"
       host: 35.233.191.155
       username: jatinnaudiyal2305
       port: 3004
       password: Jatin@12345
       pm2-id: "api"
       script: whoami 
