name: Deploying

on:
  push:
    branches:
      - testt

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v3
  
    - name: Deploy app
      uses: victorargento/pm2-deployment@main
      with:
       remote-path: "/home/jatinnaudiyal2305/jatin-naudiyal"
       host: 35.197.48.187
       username: jatinnaudiyal2305
       port: 22
       password: Jatin@12345
       pm2-id: "api"
       script: sh deploy.sh
