name: Deploying

on:
  push:
    branches:
      - apple-test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest 
    steps: 
     - name: executing remote ssh commands using ssh key
       uses: appleboy/ssh-action@master
       with:
        host: 35.197.48.187
        username: jatinnaudiyal2305
        password: Jatin@12345
        port: 22
        script: |
           whoami
           ls -al
           mkdir jatin-naudiyal
