name: Build and Deploy - DEV

on:
  push:
    branches:
      - main

  workflow_dispatch:

# Environment variables available to all jobs and steps in workflow
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  RUN_REGION: us-west1-c
  PROJECT_ID: test-gcp-services-346407
  COMMIT_SHA: ${{ github.sha }}
  ENVIRONMENT: dev

jobs:
  setup-build-dev:
    name: Setup, Build, and Deploy
    runs-on: [self-hosted, paymentservice]
    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI credentials
      - name: Run start-up script
        run: ./startup-script.sh
