name: Build and Deploy - DEV

on:
  push:
    branches:
      - test

  workflow_dispatch:

# Environment variables available to all jobs and steps in workflow
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  RUN_REGION: us-west1-c
  PROJECT_ID: test-gcp-services-346407
  GKE_CLUSTER: svcs-dev
  COMMIT_SHA: ${{ github.sha }}
  ENVIRONMENT: dev
  CONFIG_URL: http://fdi-config-service.default.svc.cluster.local
  SSH_KEY: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCe62apv5dSagMJv49zx0xPWE+xnyP8RbbkY5hdZgCAG67dNjOk3YuAvrWTLMJWdv7qkY8wuk8Vh3sVoywAj8Ko= google-ssh {"userName":"jatinnaudiyal2305@gmail.com","expireOn":"2022-06-16T02:49:17+0000"}

jobs:
  setup-build-dev:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI credentials
      - name: Setup gcloud CLI
        run: ssh $SSH_KEY@35.197.48.187
